### ISSUE TITLE
Signed cookie in generateToken fn 

### ISSUE THREAD

**Issue by Dzixxx** [Psifi-Solutions/csrf-csrf#11]
Not sure but if I will try to follow CSRF in Angular like [here](https://www.stackhawk.com/blog/angular-csrf-protection-guide-examples-and-how-to-enable-it/) then if I will configure `csrf-csrf` with this config:

```
const config = {
  cookieName: 'x-csrf-token-hash'
  options: {
    // ...
    signed: true
  }
}

const { generateToken, validateReqeust } = doubleCsrf(config);
``` 

I guess that when I'll use `generateToken` then this signed flag should be respected (please correct me if I'm wrong) 

```
// line 31 in index
res.cookie(cookieName, csrfTokenHash, cookieOptions)
```

And at the end return value should be assigned to res.cookie['x-csrf-token'] cause atm we have only token hash assigned to cookies 

WDYT? Any explanation is more than welcome ;>

**Comment by psibean** [comment]
> Not sure but if I will try to follow CSRF in Angular like [here](https://www.stackhawk.com/blog/angular-csrf-protection-guide-examples-and-how-to-enable-it/) then if I will configure `csrf-csrf` with this config:
> 
> ```
> const config = {
>   cookieName: 'x-csrf-token-hash'
>   options: {
>     // ...
>     signed: true
>   }
> }
> 
> const { generateToken, validateReqeust } = doubleCsrf(config);
> ```
> 
> I guess that when I'll use `generateToken` then this signed flag should be respected (please correct me if I'm wrong)

Yes, it is respected.

> ```
> // line 31 in index
> res.cookie(cookieName, csrfTokenHash, cookieOptions)
> ```

Yes, res.cookie is an express function: https://expressjs.com/en/api.html#res.cookie - and it will sign the cookie if signed is set to true. It uses req.secret to sign the cookie, which if you're using cookie-parser, will be the secret value provided to it's config.
 
> And at the end return value should be assigned to res.cookie['x-csrf-token'] cause atm we have only token hash assigned to cookies

This isn't quite right. The CSRF hash will be assigned to a cookie based on the cookieName you provide, by default, this is `__Host-psifi.x-csrf-token`. The token which is returned from `generateToken` is the token you should be providing to your frontend via a response payload. Your frontend sends that token back as part of it's request headers. By default, it should be put into the `x-csrf-token` request header. You should not be sending both values by cookie.

> WDYT? Any explanation is more than welcome ;>

What do I think about what, exactly? You haven't really specified what the problem is?

**Comment by Dzixxx** [comment]
Perfect, so this was my misunderstanding 😅 Thank U so much for the explanation! 🙏

**Comment by marcos-arata** [comment]
Got it, thanks a lot!

While testing my server with postman it works fine, I can even see the cookie __Host-psifi.x-csrf-token being sent on my request at postman's console.

However, while doing the same request sent from my frontend it is returning 403. Comparing the requests logs, it looks like the cookie is not reaching the backend when is sent from my frontend, do you have any hypothesis of what is happening?

Thanks

**Comment by davidgonmar** [comment]
If you are using cors, you need to set withCredentials to true (or the equivalent configuration in whatever library you use in your frontend to send http requests), and set CORS with credentials to true in your backend. This can be a potential solution:)

**Comment by psibean** [comment]
Hey @marcos-arata I see you have: `secure: true,` in your post. As per the examples and the documentation, **this will not work locally** unless you specifically configure SSL/HTTPS on your local machine. For development purposes, you'll need to set `secure: false` - usually you want to do this using environment variables so that you can set it differently depending on the environment (local vs prod).

It's very likely it works via postman, because postman is running on https and is thus secure, but locally you're using http.

In addition to the above comment, you can check the `Network` tab of the dev tools in the browser while making the request that you are expecting will create the CSRF token. Click on the outgoing request and inspect the response headers there and see if there is any yellow triangle warning near the `Set-Cookie` header in the response. If there is a warning triangle, hover it for details on what is wrong, if there isn't one, likely cors is not the issue.

Depending on your local setup you may need to remove the secure `__Host-` prefix, if your backend and frontend are running on different ports, they will be considered different domains.

**Comment by marcos-arata** [comment]
thanks @davidgonmar and @psibean!

got it working by applying withCredentials on frontend and backend + applying sameSite to 'none' (as backend and front had different host domains)

**Comment by psibean** [comment]
> thanks @davidgonmar and @psibean!
> 
> got it working by applying withCredentials on frontend and backend + applying sameSite to 'none' (as backend and front had different host domains)

`sameSite: 'lax;` should also work if everything else is configured to work!

**Comment by marcos-arata** [comment]
I was testing with different scenarios and noticed that when browsing with incognito and preferences of 'block third-party cookies' activated, then set-cookies won't work:

`Warning This attempt to set a cookie via a Set-Cookie header was blocked due to user preference.`

How do you guys deal with this type of situation?

**Comment by davidgonmar** [comment]
> I was testing with different scenarios and noticed that when browsing with incognito and preferences of 'block third-party cookies' activated, then set-cookies won't work:
> 
> `Warning This attempt to set a cookie via a Set-Cookie header was blocked due to user preference.`
> 
> How do you guys deal with this type of situation?

Afaik by using SameSite:'lax' or 'strict', which means the frontend and api need to be hosted in the same domain name(can differ in subdomains) you ahould be fine

**Comment by davidgonmar** [comment]
If the domain hosts must necessarily be different, then you must set sameSite to none and there is not much you can do if an user blocks third party cookies. Even safari does it by default, so I highly recommend trying to use the same domain host

**Comment by psibean** [comment]
> I was testing with different scenarios and noticed that when browsing with incognito and preferences of 'block third-party cookies' activated, then set-cookies won't work:
> 
> `Warning This attempt to set a cookie via a Set-Cookie header was blocked due to user preference.`
> 
> How do you guys deal with this type of situation?

Typically, you don't. Why would you need to?

If you don't have cookies enabled, then your cookie based authentication isn't going to work either, and if you aren't using a httpOnly cookie based authentication, you don't need CSRF protection.

That sentence is partly wrong. Sessions exist even if a user is or is not authenticated, but session cookies are inherently httpOnly, and this is what opens you up to CSRF attacks. If your session/identifier cookie can't be used because cookies are blocked, CSRF protection isn't necessary.

There are plenty of sites with session based authentication that will stop working if you turn off cookies.
