### ISSUE TITLE
Readme need revamp

### ISSUE THREAD

**Issue by proyb6** [Psifi-Solutions/csrf-csrf#20]
I found your readme is confusing and unorganize, if security is important.

**Comment by psibean** [comment]
Hey, I agree the readme is not the best, but in order to improve it, I'm going to need some more information.

> I found your readme is confusing 

What did you find confusing, specifically? What did you struggle with?

> and unorganize,

Did you find it difficult to find something specific?

**Comment by proyb6** [comment]
I like to use csrf-csrf on Astro (https://astro.build/) and my approach was to create new csrf on page-level, not using Astro middleware as it is still an experimental, does not seem that their tutorials with Exress works with midleware.

Is it feasible to run on page-level?

**Comment by psibean** [comment]
Are you using the [astro express integration](https://docs.astro.build/en/guides/integrations-guide/node/)? If you're using express, nothing changes, you can register the middleware before your routes, likely before the astro integration middleware, and then generate a token and provide it to your frontend by whatever means.

If you have a sample project available where you're trying to get this to work, I might be able to provide more assistance.

This is an express specific middleware, if you're using express, the examples and the guide instructions will work. If you aren't using express, it won't work. If your issue is with getting express + astro to work, you'll need to get help from them.

**Comment by proyb6** [comment]
I did tried [astro express integration](https://docs.astro.build/en/guides/integrations-guide/node/) with Node but I don't understand how it can get csrf-csrf token to render in HTML form on page-level.

ps. I read that you have a discussion https://github.com/NodeBB/NodeBB/issues/11046 on integration, my thought if it is useful for your package to work with Astro integration? It will be perfect if it work as the community is focus on havin a great PageSpeed score.

**Comment by psibean** [comment]
> I did tried [astro express integration](https://docs.astro.build/en/guides/integrations-guide/node/) with Node but I don't understand how it can get csrf-csrf token to render in HTML form on page-level? 

Okay so I've taken a bit of a look at the astro documentation and you have a couple of options:

1. You can create an [astro middleware](https://docs.astro.build/en/guides/middleware/) which calls the `generateToken` function and provides the token as a local variable for use in your astro template; or 
2. You can create your own [astro endpoint](https://docs.astro.build/en/core-concepts/endpoints/) which calls the `generateToken` function and returns the token in a response.

For option 2, your frontend would ake a request to get a token when it needs it, and you should make the tokens user scoped (so that a valid generated token can only be used by the user who requested it). There are a couple of ways you can achieve this, such as generating secrets at runtime on a per user session basis. Or by storing the token server side against the users session, but if you're using user sessions with state, then you'd be better off using csrf-sync instead.

**Comment by proyb6** [comment]
If a public user submission forms e.g. contact form, or forgot password form, could use option 2 to store token in Redis with expiry time is ideal? I assume the csrf-sync would be used when user is logged in.

**Comment by psibean** [comment]
>could use option 2 to store token in Redis with expiry time is ideal?

If your token is user scoped, and your user session already has an expiry time (which it should), then having a csrf token expiry is redundant, as it will expire along with the session if done correctly.

>I assume the csrf-sync would be used when user is logged in.

Why do you assume that? If you're using session based authentication, then even non-authenticated (anonymous) users, still have a session associated with them. If a user who is not yet logged in does not have a csrf token, how are you protecting the login route?

**Comment by psibean** [comment]
The README has had some updates, though they aren't particularly related to the concerns here (which still aren't very clear).

If you're still having problems or would like to point out some specific things that are unclear.

Generally it's up to yo to understand the overall tech stack you're using. If you have a clear understanding of your techstack, and your techstack uses express under the hood, and you understand how middleware works, it shouldn't be too difficult to get the csrf-csrf middleware working.

It's not up to the csrf-csrf documentation to explicitly advise on how to get it working with every possible express based abstraction - these should instead be included as examples under the examples directory.

PR's providing new examples are welcome.
