### ISSUE TITLE
Token inaccessible from req.headers

### ISSUE THREAD

**Issue by Jawad-Ali2** [Psifi-Solutions/csrf-csrf#52]
Hello, I am trying to add double-csrf token on my react + nodejs application but I am facing an issue relating to passing tokens on headers through my client side. I went through the code and saw this: 
![image](https://github.com/Psifi-Solutions/csrf-csrf/assets/107391644/9bcf3e58-622a-4c9c-98d0-e2219a52f79e)

When the token is generated httpOnly is set to true. I know the csrf token isn't meant to be accessed on the client side. But the issue is when _getTokenFromRequest_ function is called. It searches for the token in _req.headers_ but the token isn't there.
![image](https://github.com/Psifi-Solutions/csrf-csrf/assets/107391644/cf8d10ad-32b2-4eb0-8635-21323c0db1b4)

![image](https://github.com/Psifi-Solutions/csrf-csrf/assets/107391644/1cc03e7f-cd72-4b7f-8623-e1f42c12592c)
![image](https://github.com/Psifi-Solutions/csrf-csrf/assets/107391644/ff8a6b46-e6f5-460f-be71-98631640865d)

 I've read and implemented the documentation many times but am still unable to do it.

Here's my code for the backend and the client's POST request.
![code](https://github.com/Psifi-Solutions/csrf-csrf/assets/107391644/8ed058a1-d0f1-4bfe-a724-ebd83a5bdf64)

POST Request:
![code1](https://github.com/Psifi-Solutions/csrf-csrf/assets/107391644/a29e13f5-1298-49c2-9eba-9b0993410813)

Can you kindly take a look? I would appreciate it. Thanks.

**Comment by psibean** [comment]
> Can you kindly take a look? I would appreciate it. Thanks.

You're generating a token using `generateToken` but you aren't using the return value, which you need to do. I suggest you take a look at the examples included in the repo under the examples folder. It is expected that you should be familiar with the Double Submit Token pattern and how it works, as you need to understand how it works in order to decide whether it fits your use case or whether you're better off using `csrf-sync`.

`generateToken` returns the token value, you need to send that value to your frontend (in the case of SSR, you can provide it inside a template response), if you're rolling an SPA, you'll likely need an endpoint for retrieving a csrf-token and you'll want to make sure the use of that token is explicitly limited to a specific session. This value is what you need to include in your header (or form body), the browser will send the cookie value (containing the hashed token) automatically, then `csrf-csrf` middleware will compare the token value in the header with the hashed token value in the cookie.

**Please do not post screenshots, you should post actual codeblocks**

```js
console.log('Like this');
```
By posting screenshots I'm not able to show you the exact code that is wrong.

**Comment by Jawad-Ali2** [comment]
First of all. Sorry about sending screenshots and not the code blocks, and thanks for your response. Secondly, I was at first worried that sending the token through a request would expose the token to the public through **request payload**. But now that I have gone through the documentation again I realized that the token can never be verified without the secret.
Now as I am making a MERN application, I just create an endpoint of `/get-token` and call it each time my application first loads up, that way I get the token on my frontend useState and just send that token with each `GET` or `POST` request. The backend will verify that token and verify it. Am I right? Please correct me if I am wrong.

**Comment by psibean** [comment]
> First of all. Sorry about sending screenshots and not the code blocks, and thanks for your response.

No worries, just something to note and be wary of! Posting images of code is generally frowned upon within almost all code support communities.

> Secondly, I was at first worried that sending the token through a request would expose the token to the public through **request payload**. 

Not sure what you mean here. If you make a request (POST, PUT, or PATCH) with the token inside of the request payload, how is that going to be public? You should be using `https` (ssl) in production, and if you have any other kind of vulnerability where an attacker is accessing the payloads of requests to your server, then CSRF attacks are the least of your worries.

If you meant response payloads, CSRF attacks don't have access to response content. However, if you provide an endpoint specifically for generating and providing a CSRF token to the frontend, then you need to make sure that token can only be used by the user who requested it. Otherwise anyone can request a CSRF token and then use that with someone else's session, typically `csrf-sync` is a better option here as it already ties the token to a specific session, but it does require server-side session state.

> Now as I am making a MERN application, I just create an endpoint of `/get-token` and call it each time my application first loads up, that way I get the token on my frontend useState and just send that token with each `GET` or `POST` request. The backend will verify that token and verify it. Am I right? Please correct me if I am wrong.

As mentioned, you'll need to make sure that a token will only work for a specified user session in this case, typically you'll be better off using `csrf-sync` instead.

Additionally, `GET` requests should not need protection because they should not be making any writes or server-side state changes. You should make sure you only use `GET` requests to receive stuff. You should not make any database updates or changes in a get request (perhaps with the exception of analytics and other such things). Make sure you're using the proper and appropriate request types for the behaviour of the endpoints (PATCH, PUT, POST, DELETE, etc)

**Comment by Jawad-Ali2** [comment]
Thanks a lot, man. I learned a lot about csrf tokens. I think I'll migrate to `csrf-sync`. I was unaware of that package, when I searched for csrf package only `csrf-csrf` popped up on my screen and I started using that. One last thing is do you stay active on your discord channel? I would like you to help me if I face any issue related to the implementation of `csrf-sync` . Anyway, my issue has been resolved. Thanks for your response @psibean and thanks for working on alternative solutions for `csurf`. Appreciate your efforts!

**Comment by psibean** [comment]
> Thanks a lot, man. I learned a lot about csrf tokens. I think I'll migrate to `csrf-sync`. I was unaware of that package, when I searched for csrf package only `csrf-csrf` popped up on my screen and I started using that. One last thing is do you stay active on your discord channel? I would like you to help me if I face any issue related to the implementation of `csrf-sync` . Anyway, my issue has been resolved. Thanks for your response @psibean and thanks for working on alternative solutions for `csurf`. Appreciate your efforts!

No problem! Am typically active on Discord quite a lot.
