### ISSUE TITLE
Cookie invalid prefix

### ISSUE THREAD

**Issue by juan-cyb** [Psifi-Solutions/csrf-csrf#65]
Hello, I'm troubleshooting a cookie issue with my own app, which uses [cookie-session](https://www.npmjs.com/package/cookie-session).

I'm going back to basics and trying your [complete example](https://github.com/Psifi-Solutions/csrf-csrf/tree/main/example/complete), which works. However, I'm now slowly introducing the changes present in my own app to see if I can re-create the issue.

The first thing I did was
- comment out `// cookieName: CSRF_COOKIE_NAME,`
- change the cookie name in index.html: `"__Host-psifi.x-csrf-token": token, // comment this line to throw an error.` 

But I'm now getting this "invalid prefix" warning in Firefox, and I see no cookies with name `__Host-psifi.x-csrf-token` being set, so CSRF validation now fails.

![image](https://github.com/Psifi-Solutions/csrf-csrf/assets/165780746/2178179d-e22b-42d1-b731-a906fe820d81)

This might actually be related to my own issue:

```
Listening on port 8555...
Server Stopped
/home/opyate/my-app/node_modules/csrf-csrf/lib/cjs/index.cjs:65
        : (req) => req.cookies[cookieName];
                              ^
TypeError: Cannot read properties of undefined (reading '__Host-psifi.x-csrf-token')
    at getCsrfCookieFromRequest (/home/opyate/my-app/node_modules/csrf-csrf/lib/cjs/index.cjs:65:31)
    at generateTokenAndHash (/home/opyate/my-app/node_modules/csrf-csrf/lib/cjs/index.cjs:40:28)
    at generateToken (/home/opyate/my-app/node_modules/csrf-csrf/lib/cjs/index.cjs:58:46)
    at IncomingMessage.req.csrfToken (/home/opyate/my-app/node_modules/csrf-csrf/lib/cjs/index.cjs:92:57)
    at /home/opyate/my-app/src/server/controllers/questions/selectCountry.controller.ts:35:125
    at Generator.next (<anonymous>)
    at /home/opyate/my-app/src/server/controllers/questions/selectCountry.controller.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/opyate/my-app/src/server/controllers/questions/selectCountry.controller.ts:4:12)
    at get (/home/opyate/my-app/src/server/controllers/questions/selectCountry.controller.ts:23:12)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by juan-cyb** [comment]
This is in package.json, but isn't the latest release 3.0.6?

![image](https://github.com/Psifi-Solutions/csrf-csrf/assets/165780746/6bcc744a-cb6a-4e83-b121-c0c3ce1f02b0)

**Comment by psibean** [comment]
> But I'm now getting this "invalid prefix" warning in Firefox, and I see no cookies with name __Host-psifi.x-csrf-token being set, so CSRF validation now fails.

Yes. `__Host-` is a security feature of cookie, you can find some documentation at [MDN - Cookie Prefixes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#cookie_prefixes). You should be familiar with what the implications of the prefix are and decide whether or not it is suitable for your usecase, if it is not suitable for your usecase, then you will need to provide a cookie name that does not include the prefix.

> TypeError: Cannot read properties of undefined (reading '__Host-psifi.x-csrf-token')

What this error is saying is it's trying to read a property by the name `__Host-psifi.x-csrf-token` off of some object, it's the object that is actually undefined. 

```js
(req) => req.cookies[cookieName];
```

Here the cookieName is a variable which holds the value `__Host-psifi.x-csrf-token` which is the property being read on the `req.cookies` object. The error is telling you that `req.cookies` is undefined, and you can't do `undefined[cookieName]`. Because that's not valid.

This usually indicates that you haven't registered the `cookie-parser` middleware **before** the csrf-csrf middleware.

Regarding the first thing you did:

> change the cookie name in index.html: "__Host-psifi.x-csrf-token": token, // comment this line to throw an error.

There is no cookie name in the `index.html` so you've done something very wrong here. The HTML does not access the cookie at all, it access the token value from inside the response body payload. By default, the double submit cookie pattern has a `httpOnly` cookie which contains the token hash, not the token itself.

If you changed this line:

```js
"x-csrf-token": token
```

That's the header the token is being sent in, not a cookie at all. The cookie is sent automatically by the browser, it doesn't need to be manually included into the request.

> This is in package.json, but isn't the latest release 3.0.6?

Yeah, 3.0.6 is the latest at the moment, but it's on it's own release branch as there were some TypeScript issues with the 3.0.4 release. I need to fix up the build and set up an automerge strategy for release branches.

**Comment by juan-cyb** [comment]
> Yes. __Host- is a security feature of cookies, you can find some documentation at [MDN - Cookie Prefixes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#cookie_prefixes). You should be familiar with what the implications of the prefix are and decide whether or not it is suitable for your usecase, if it is not suitable for your usecase, then you will need to provide a cookie name that does not include the prefix.

Ah, thanks for that.

> This usually indicates that you haven't registered the cookie-parser middleware before the csrf-csrf middleware.

My bad :) I actually use `cookie-session` instead of `express-session` and managed to make a really simple CSRF middleware:

```
// middleware.ts
import crypto from "crypto";
import { Express } from "express";
import type { Request, Response, NextFunction } from "express";

export function configureCSRF(app: Express): void {
  const handler = (req: Request, res: Response, next: NextFunction) => {
    if (!req.session.csrfToken) {
      const csrfToken = crypto.randomBytes(32).toString('hex');
      req.session.csrfToken = csrfToken;
    }
    res.locals.csrfToken = req.session.csrfToken; // This makes the token available in the views
    next();
  };

  app.use(handler as any);
}

export function verifyCsrfToken(req: Request, res: Response, next: NextFunction) {
  const tokenFromBody = req.body._csrf;
  const tokenFromSession = req.session.csrfToken;

  if (!tokenFromBody || tokenFromBody !== tokenFromSession) {
    return res.status(403).send('CSRF token validation failed');
  }

  next();
}

// routes.ts
router.post("/", verifyCsrfToken, postHandler);

// view.njk
  <form method="post">
    <input type="hidden" name="_csrf" value="{{csrfToken}}">

```

**Comment by psibean** [comment]
> > Yes. __Host- is a security feature of cookies, you can find some documentation at [MDN - Cookie Prefixes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#cookie_prefixes). You should be familiar with what the implications of the prefix are and decide whether or not it is suitable for your usecase, if it is not suitable for your usecase, then you will need to provide a cookie name that does not include the prefix.
> 
> Ah, thanks for that.
> 
> > This usually indicates that you haven't registered the cookie-parser middleware before the csrf-csrf middleware.
> 
> My bad :) I actually use `cookie-session` instead of `express-session` and managed to make a really simple CSRF middleware:
> 
> ```
> // sesstion.ts
> export interface SessionData {
>   // ... etc
>   csrfToken?: string;
> };
> 
> declare module "express" {
>   interface Request {
>     session: SessionData;
>   }
> }
> 
> 
> // middleware.ts
> import crypto from "crypto";
> import { Express } from "express";
> import type { Request, Response, NextFunction } from "express";
> 
> export function configureCSRF(app: Express): void {
>   const handler = (req: Request, res: Response, next: NextFunction) => {
>     if (!req.session.csrfToken) {
>       const csrfToken = crypto.randomBytes(32).toString('hex');
>       req.session.csrfToken = csrfToken;
>     }
>     res.locals.csrfToken = req.session.csrfToken; // This makes the token available in the views
>     next();
>   };
> 
>   app.use(handler as any);
> }
> 
> export function verifyCsrfToken(req: Request, res: Response, next: NextFunction) {
>   const tokenFromBody = req.body._csrf;
>   const tokenFromSession = req.session.csrfToken;
> 
>   if (!tokenFromBody || tokenFromBody !== tokenFromSession) {
>     return res.status(403).send('CSRF token validation failed');
>   }
> 
>   next();
> }
> 
> // routes.ts
> router.post("/", verifyCsrfToken, postHandler);
> 
> // view.njk
>   <form method="post">
>     <input type="hidden" name="_csrf" value="{{csrfToken}}">
> ```

Yep, that works.

It looks like you're using the synchronised token pattern here, not the double submit pattern - which is what csrf-csrf is for. The implementation you have here is what `csrf-sync` is for, which would likely have worked better for you.
