### ISSUE TITLE
Is the endpoint `/csrf-token` shown in the examples actually needed for protection?

### ISSUE THREAD

**Issue by strazto** [Psifi-Solutions/csrf-csrf#75]
In all of your examples (& userdocs), you demonstrate a separate GET route `/csrf-token` that returns the generated token.

https://github.com/Psifi-Solutions/csrf-csrf/blob/3a016c5a849521994f73121c8e58521efb1b421c/example/complete/src/index.js#L48-L52

I'm not clear on whether this separate endpoint is intended to demonstrate the use of a manual `generateToken` call, or if it's actually necessary for the operation of the middleware.

I've reviewed the source, and it looks like it's not necessary to implement this endpoint.

Am I correct in thinking this?

**Comment by psibean** [comment]
Correct, it's not necessary! However you will need to `generateToken` at some point in order to have a token, and you do need to return the value from `generateToken` to your frontend in some way, either as part of a request, or as part of a server rendered response.

In a case where you have an SPA which is not served by the express app, you'd likely need a specific endpoint, or an initial data fetching end point, that includes a CSRF token. Alternatively, if your SPA is served by your express app, you could inject the csrf token into a meta tag on the entry page to the frontend.

**Comment by psibean** [comment]
Closing this for now, feel free to comment back and re-open if you're still uncertain. If you have any other issues/concerns, feel free to raise another issue.
