### ISSUE TITLE
Invalid CSRF token when accessing on IP address

### ISSUE THREAD

**Issue by chr15m** [Psifi-Solutions/csrf-csrf#76]
I noticed a weird issue. When I am developing on my local (localhost:8000) the library works well. When I deploy it works well and there it is also served on localhost behind an nginx proxy.

However when I am trying to test on my local network by binding my dev server to 0.0.0.0 instead of localhost, and I access via the IP address of my laptop from my phone, I get an invalid CSRF token error. Are the tokens somehow sensitive to the IP address of the server or client?

**Comment by psibean** [comment]
> Are the tokens somehow sensitive to the IP address of the server or client?

Not at all, this is likely to do with the request now being considered cross-site (third-party), and so the browser may not be including the cookie in the outgoing request.

You'll need to make sure your backend has CORs configured such that it will accept cookies from the cross-site request. You may need to set your `sameSite` cookie setting to `none` for this usecase. You'll also need to make sure you set `credentials: true` on the `fetch` request.

A slight alternative would be to configure a local DNS entry on your local network, say something like `localdev.web`, to route through to your laptop. Configure a locally static IP for your laptop, say `192.168.0.150`, then have a DNS on your local network resolve `localdev.web` to your `192.168.0.150:8000`, such that it'll hit your nginx proxy, then anywhere on your local network, access via `http://localdev.web`.

**Comment by chr15m** [comment]
@psibean thanks for the quick response! Ah ok, yes, that makes sense. When I set `sameSite` to `none` and `secure` to `false` the error goes away. I'll have to figure out how to accommodate this use-case in my web framework. :thinking: Many thanks!

**Comment by psibean** [comment]
Yep, these are things that typically differ between local dev and a real deployment. If you have a docker setup, you can try and get a closer to production development environment, for example, you could generate an SSL certificate using Lets Encrypt and then make use of it in the container to serve the site over https, this way you can keep `secure: true`

The more common way is to have these things configured by environment variables, and in production, actually have those environment variables configured on the host, or otherwise have some kind of secrets manager.
